name: Generate README

on:
  workflow_call:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout awesome-nan
        uses: actions/checkout@v2
        with:
          repository: nanlabs/awesome-nan
          path: awesome-nan

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.30

      - name: Generate README
        run: |
          # Generate the README
          ./awesome-nan/tools/readme-generator/main.ts README.md.tmpl examples.json

      - name: Run prettier
        run: npx prettier --write README.md

      - name: Run markdownlint
        uses: articulate/actions-markdownlint@v1
        with:
          fix: true

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update README"
          add: README.md
