storage: /verdaccio/storage
max_body_size: 500mb
uplinks:
  nanlabs:
    url: http://nexus.internal.nanlabs.com/repository/npm-nanlabs/
packages:
  "**":
    access: $all
    publish: $all
    unpublish: $all
    proxy: nanlabs
middlewares:
  audit:
    enabled: true
logs:
  - { type: stdout, format: pretty, level: trace }
